// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 23 Mar 2026 22:04:09 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package NDI provides go bindings for the Newtek NDI SDK
*/
package ndigo4
